name: 'ExtractPassword'
on:      
  workflow_dispatch:
 
jobs: 
  Deploy:
    name: ExtractPassword
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
 
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DUMMY_CREDENTIALS }}
        enable-AzPSSession: true
      
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      azPSVersion: 'latest'
      with:
        inlineScript: |
          $credentials = ${{ secrets.AZURE_DUMMY_CREDENTIALS }}
          $objectSecret = @()
          $objectSecret = ConvertFrom-Json $credentials
          [string]$servicePrincipalId = ($objectSecret).clientId
          [string]$servicePrincipalKey = ($objectSecret).clientSecret
          [string]$tenantId = ($objectSecret).tenantId
          Write-Output "servicePrincipalId"
          $servicePrincipalId | Format-Hex | Select-Object -Expand Bytes | ForEach-Object { '{0:x2}' -f $_ }) -join ''
          Write-Output "servicePrincipalKey"
          $servicePrincipalKey | Format-Hex | Select-Object -Expand Bytes | ForEach-Object { '{0:x2}' -f $_ }) -join ''
          Write-Output "tenantId"
          $tenantId | Format-Hex | Select-Object -Expand Bytes | ForEach-Object { '{0:x2}' -f $_ }) -join ''
