name: 'ExtractPassword'
on:      
  workflow_dispatch:
 
jobs: 
  Deploy:
    name: ExtractPassword
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
 
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DUMMY_CREDENTIALS }}
        enable-AzPSSession: true
      
    - name: Extract
      env:
        CREDENTIALS: ${{ secrets.AZURE_DUMMY_CREDENTIALS }}
      run: ./powershell/get_sp.ps1
      shell: pwsh
